AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - ./spec/**/*

Gemspec/RequireMFA:
  Enabled: false
