name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.7.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Install dependencies
        run: make install

      - name: Run RSpec
        run: make test
